#!/usr/bin/env ruby

if ARGV.length < 1
  puts "Usage: ruby provision 127.0.0.1"
  exit
end

class Provisioner
  attr_reader :host

  def initialize(host)
    @host = host
  end

  def run
    `scp setup.sh root@#{host}:/root/setup.sh`
    `scp sshd_config root@#{host}:/root/sshd_config`
    `scp -r chef root@#{host}:/var/chef`
  end
end

Provisioner.new(ARGV[0]).run
